-- Supabase Dashboard > SQL Editor에서 한 번 실행합니다.
-- 두 표는 서버의 비밀 키로만 접근하며 브라우저 키에는 권한을 주지 않습니다.

create table if not exists public.content_entries (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('post', 'review')),
  category text not null,
  title text not null,
  body text not null,
  format text not null default 'text' check (format in ('text', 'html')),
  cover_image text,
  sample boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  goal text not null,
  education text not null,
  message text not null default '',
  calculator jsonb
);

alter table public.content_entries enable row level security;
alter table public.consultations enable row level security;
revoke all on public.content_entries, public.consultations from anon, authenticated;
revoke all on sequence public.content_entries_id_seq, public.consultations_id_seq from anon, authenticated;
grant all on public.content_entries, public.consultations to service_role;
grant usage, select on sequence public.content_entries_id_seq, public.consultations_id_seq to service_role;

insert into storage.buckets (id, name, public)
values ('mentor-images', 'mentor-images', false)
on conflict (id) do nothing;

insert into public.content_entries (type, category, title, body, sample)
select type, category, title, body, true
from (values
  ('post', '학위취득', '학위 취득 안내 글 예시', '게시판 형식을 확인하기 위한 예시 글입니다. 실제 교육과정 안내로 교체해 주세요.'),
  ('post', '편입', '편입 준비 안내 글 예시', '편입 게시판의 예시 글입니다. 지원 대학의 실제 모집 요강을 확인한 뒤 내용을 작성해 주세요.'),
  ('review', '학위취득', '학생 후기 예시', '이 카드는 후기 화면을 보여주는 샘플입니다. 실제 학생의 경험담이 아닙니다.')
) as seed(type, category, title, body)
where not exists (select 1 from public.content_entries);
